[build]
no_sri = true
filehash = false
offline = false
dist = "../dist"
# Require Cargo.lock and cache are up to date
frozen = true
# Require Cargo.lock is up to date
locked = true

[serve]
# The address to serve on.
address = "0.0.0.0"
# The port to serve on.
port = 8080
